name: My Second Practice

on:
  push:
   branches:
    - main

jobs:
 test:
  runs-on: ubuntu-latest

  steps:
   - name: Step One
     run: echo "Weldone"
    
   - name: Step Two
     run: echo "you are trying my dear"

   - name: Step Three
     uses: action/checkout@v4

  










